### ISSUE TITLE
BUG: Failure at MOCalculator.cpp:65/getStoreOffset()!

### ISSUE THREAD

**Issue by lilith218** [MPI-SWS/genmc#45]
BUG: Failure at MOCalculator.cpp:65/getStoreOffset()!

This bug occurs on v0.8 when` -imm` and `-nthreads=10 ` are used on some clients. I did not have the time yet to find a small client for it.

**Comment by db7** [comment]
We also experienced that. In our case, it happened with `-nthreads=1` but only with specific random seeds.

**Comment by michaliskok** [comment]
Thanks for the report; if you could send me a test that reproduces it, that would be great.

[I have rewritten a large part of that particular infrastructure that perhaps fixes this bug as well, but the new version will not be ready before early August.]

**Comment by db7** [comment]
Here is a small example... I couldn't simplify it more.

```c
#define __CONFIG_GENMC_INODE_DATA_SIZE 64
#include <pthread.h>
#include <stdlib.h>
#include <assert.h>
#include <stdint.h>

typedef struct {
    uint64_t r;
    uint64_t y;
    uint64_t t;
} T;

T* q;

#define barrier() asm("")
void     STORE(uint64_t *a, uint64_t v) {barrier();__atomic_store_n(a, v, __ATOMIC_SEQ_CST);}
uint64_t LOAD(uint64_t *a) {barrier();return __atomic_load_n(a, __ATOMIC_SEQ_CST);}

void *thread1 (void *args)
{
    uint64_t x[1];
    for (int j = 0; j < 1; j++)
        x[j] = 1UL;

    q->r = x[0];
    __atomic_store_n(&q->y, 0, __ATOMIC_RELAXED);
    return NULL;
}

void *thread2 (void *args)
{    
    LOAD(&q->y);
    assert(q->r);
    return NULL;
}

int
main(int argc, char **argv)
{
    q = (T*) malloc(sizeof(T));
    STORE(&q->y, 0);
    STORE(&q->t, 0);
    STORE(&q->y, 0);

    pthread_t t1, t2;
    pthread_create(&t1, NULL, thread1, 0);
    pthread_create(&t2, 0, thread2, 0);
    pthread_join(t2, 0);
  
    return 0;
}
```

Output:
```
$ genmc -imm -random-schedule-seed=3 -schedule-policy=random mo-bug.c
BUG: Failure at MOCalculator.cpp:65/getStoreOffset()!
```

**Comment by michaliskok** [comment]
Fixed in v0.9; thanks again.

**Comment by lilith218** [comment]
@michaliskok unfortunately, we still encounter this bug on different clients with GenMC 0.9 as well. Please reopen it. I will try to find more information that could help debugging it, once I have some free time.

**Comment by michaliskok** [comment]
Should be fixed in v0.10.0
